name = "testerpartner"

compatibility_date = "2026-07-15"

pages_build_output_dir = "./"

[vars]
TIMEZONE = "America/Argentina/Buenos_Aires"
SESSION_DURATION = "30"
BUFFER_MINUTES = "15"

AIRTABLE_BASE_ID = "TU_BASE_ID"
AIRTABLE_TABLE = "TU_TABLE_ID"

GOOGLE_CLIENT_ID = "738192917531-g1rjejs674ts8k78qehn4gjakdgnaogo.apps.googleusercontent.com"
GOOGLE_REDIRECT_URI = "https://testerpartner.pages.dev/api/google/callback"
GOOGLE_CALENDAR_ID = "primary"